gitlab_token               = "QWw3Up5eypuvbjweY7zZ"
gitlab_url                 = "http://localhost/api/v4/"
gitlab_commit_author_name  = "The Terminator"
gitlab_commit_author_email = "hasta.la.vista@baby.com"
owner                      = "Mattermost"