---

instance:
  hooks:
  - name: "Sample Hook"
    tokenSecret: "sample_hook_token"
    url: "https://localhost:9090"
    flags:
      - EnableSslVerification
      - MergeRequestsEvents
      - PushEvents
      - RepositoryUpdateEvents
      - TagPushEvents
  vars:
  - key:  "instance_variable_key"
    valueSecret: "secret1"
    type: "env_var"
    flags:
      - Masked
      - Protected
  - key:  "instance_variable_file"
    valueSecret: "secret2"
    type: "file"
    flags:
      - Masked
      - Protected        
...